version: '3'
services:
   notebook-server:
      build: .
      ports:
         - "8888:8888"
      volumes:
         - data:/data
         - ./:/shareddata
      # entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash"
      stdin_open: true
      tty: true

volumes:
  data: